spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dbserver:3306/testdb?useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.newqur.entities
  config-location: classpath*:mybatis-config.xml
  mapper-location: classpath*:com/newqur/mapper/*Mapper.xml
